name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: add source
      run: nuget sources add -name github -username s-anupam -password ${{ secrets.github_token }} -StorePasswordInClearText -source "https://nuget.pkg.github.com/s-anupam-nuget-billing/index.json"
    - name: install package
      run: for i in {1..10}; do rm -rf * && nuget locals all -clear && nuget install LargePvt -Version 1.0.0 -Source "https://nuget.pkg.github.com/s-anupam-nuget-billing/index.json"; done
